[package]
name = "git-sift"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
git2 = "0.20.2"
ratatui = "0.29.0"

[[bin]]
name = "sift"
path = "src/main.rs"

